In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn import datasets

C:\anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
data1 = np.genfromtxt("train_diabetes.csv",delimiter = ",")
data2 = np.genfromtxt("test_diabetes.csv",delimiter = ",")

In [3]:
data1.shape

(331, 11)

In [4]:
data2.shape

(111, 10)

In [19]:
x_train = data1[0:,0:10]
y_train = data1[:,10]

In [21]:
x_test = data2[0:,0:10]


In [22]:
print(x_test.shape)


(111, 10)


In [23]:
print(x_train.shape)
print(y_train.shape)

(331, 10)
(331,)


In [24]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg1.fit(x_train,y_train)

LinearRegression()

In [25]:
alg1.coef_

array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
       -833.11088526,  525.74313633,  136.07129167,  140.89458927,
        731.44498492,   53.32119133])

In [26]:
alg1.intercept_

150.702574894566

In [27]:
y_pred = alg1.predict(x_test)
y_pred

array([105.52974799, 105.8039198 , 178.60857225,  79.3828781 ,
        52.95868706,  98.87263854, 150.71755448,  34.86515216,
       113.13535727, 161.50184038, 135.8615611 ,  94.71592222,
       138.48094422, 141.37441723, 158.76862662, 171.65288616,
       106.44835654, 103.92659639,  95.38693889, 167.40118092,
       166.53426278, 101.53464712, 252.45035972, 147.02258547,
       214.78906632, 161.27557106, 210.61315228,  71.78091585,
       189.65032431, 206.6134259 , 219.98643455, 168.80192534,
       116.84846127, 178.74399639,  77.03247418,  59.54633214,
       111.5673781 , 156.95186739, 154.59591259, 198.94457493,
       115.53884017, 153.46699024,  84.96179518, 113.70337192,
       142.14155617, 147.31040378,  82.78072358,  77.89237327,
       128.99006192, 261.58712282, 213.31187775, 243.98791257,
       167.68132094, 183.69712124, 166.85926884, 202.11440188,
       220.39235543, 172.40288024, 176.60897931, 109.04656567,
       276.37789836,  90.99941821, 289.37221147, 119.56

In [28]:
save = np.savetxt('ypredictfinal1.csv',y_pred,delimiter=',',fmt = "%.5f")
save

In [29]:
final_data = np.genfromtxt("ypredictfinal1.csv",delimiter = ",")
final_data

array([105.52975, 105.80392, 178.60857,  79.38288,  52.95869,  98.87264,
       150.71755,  34.86515, 113.13536, 161.50184, 135.86156,  94.71592,
       138.48094, 141.37442, 158.76863, 171.65289, 106.44836, 103.9266 ,
        95.38694, 167.40118, 166.53426, 101.53465, 252.45036, 147.02259,
       214.78907, 161.27557, 210.61315,  71.78092, 189.65032, 206.61343,
       219.98643, 168.80193, 116.84846, 178.744  ,  77.03247,  59.54633,
       111.56738, 156.95187, 154.59591, 198.94457, 115.53884, 153.46699,
        84.9618 , 113.70337, 142.14156, 147.3104 ,  82.78072,  77.89237,
       128.99006, 261.58712, 213.31188, 243.98791, 167.68132, 183.69712,
       166.85927, 202.1144 , 220.39236, 172.40288, 176.60898, 109.04657,
       276.3779 ,  90.99942, 289.37221, 119.56253,  75.45688, 180.78599,
       146.62093, 156.42382,  41.07904, 247.90645, 207.99121,  90.09641,
       222.2417 , 189.86378, 182.26954, 164.39881, 190.27067, 105.44868,
       199.86136, 245.79639, 123.20281, 119.41032, 